### ISSUE TITLE
Allow for web version keyboard shortcuts

### ISSUE THREAD

**Issue by kaicarver** [skritter/skritter-html5#139]
on a PC, keyboard shortcuts are very useful for zipping through items.

I especially use the arrow keys:
* up: show
* down: mark incorrect or correct
* right: next item
* left: previous item

and the digits 1,2,3,4 for grading more precisely than correct/incorrect
I also use 'a' to hear the audio and 'd' to see the information window.

the full list of Skritter keyboard shortcuts is here:
http://www.skritter.com/faq#shortcuts

keyboard shortcuts would also make it easier to test the web app.

**Comment by mcfarljw** [comment]
http://docs.skritter.com/article/78-keyboard-shortcuts
