### ISSUE TITLE
[Minor] 0.70.2331 on Samsung Galaxy S3 running Android 4.1 - Better slow connection and timeout handling.

### ISSUE THREAD

**Issue by intermaggio** [skritter/skritter-html5#313]
I can't properly test this in my current setting, but a couple of days ago when I was on 0.70.2331 with a very slow connection (Wi-Fi tethered to a 3g cellphone in a stadium crowded with fellow data hogs), I found that attempting to do anything in the app requiring data connection didn't appear to have any timeout handling- at least not within 30-60 seconds, which is plenty of time for a user (myself included) to get discouraged without some indication of progress or error. 

I consider this a bug rather than a feature enhancement as I haven't yet seen whether it would throw a timeout error connected to a network with no data.

**Comment by mcfarljw** [comment]
I'm closing some previous Android issues to focus on the latest https://html5.skritter.com changes. They will eventually make their way onto Android as an update.
