### ISSUE TITLE
Data lost when logged out

### ISSUE THREAD

**Issue by sderickson** [skritter/skritter-html5#339]
I have been studying most days this month, but I haven't been hitting the sync button. Today I found I was logged out when I opened the app, possibly the cookie had expired. Anyway I logged in and whereas I was expecting just a few dozen reviews, I have over 150 and no indication I've studied this month. Either the app should sync automatically and regularly when it's online, or logging into your account should not overwrite locally stored reviews. Maybe both?

**Comment by mcfarljw** [comment]
This has been fixed in the latest 2.0 beta!
