### ISSUE TITLE
Navigating backwards and forwards results in squigs being replaced by strokes

### ISSUE THREAD

**Issue by mcfarljw** [skritter/skritter-html5#349]
This was reported by @sderickson. It can be reproduced by switching on raw squigs, partially completing a prompts, navigating backwards and then forwards. The partially drawn squigs are replaced by actual strokes rather than the partially drawn squigs.

**Comment by mikemills** [comment]
#340 is also not quite fixed - left a comment there but I can't see how to reopen it.
