### ISSUE TITLE
No sound at all, intended?

### ISSUE THREAD

**Issue by DavidDanielsson** [skritter/skritter-html5#366]
I have no sound at all in the html5 version of Skritter. It's been like this for a couple of weeks now in both Chrome and Firefox on my Ubuntu 14.04 desktop, but also in Chrome and Firefox in my Virtualboxed Windows 8.1.

I figured that since there's no sound anywhere this is intentional, but I can't find anything about sound being disabled. Is it intended?

Sound is on in my settings

**Comment by mcfarljw** [comment]
It wasn't intentional, but I just uploaded a fix (commit 29f1b1641d80751e48589bb3cddbd966677ecd8d) to production that should fix this issue.
