### ISSUE TITLE
Stub out mixpanel if it didn't load

### ISSUE THREAD

**Issue by nwinter** [skritter/skritter-html5#409]
Certain adblockers will  make mixpanel not load. In https://github.com/skritter/skritter-html5/blob/14234c1708f9fe32d55b5690212fc306d9086a28/app/application.js we need to turn `mixpanel` into a stub with `{track: function() {}}` and not register it. Then it won't error out and cause the site to not load.

**Comment by nwinter** [comment]
Now it says `Unable to init mixpanel` correctly as a warning, cool, then errors immediately: `ScreenLoader is not defined`. Works if I disable this (common) adblocker. Same bug incompletely fixed, or a different bug?

**Comment by mcfarljw** [comment]
I think Michael fixed this here (https://github.com/skritter/skritter-html5/commit/24437b0fe07807c6b1ee9a237f2c874fb006ec2a) but it hasn't been pushed live yet. I should probably do that soon!
