### ISSUE TITLE
Info dialog backend service needs a wrapper (as it is very very slow)

### ISSUE THREAD

**Issue by mickem** [skritter/skritter-html5#423]
Currently the backend service for the info dialog needs to have a wrapper as it makes waaaay to many calls.

![image](https://cloud.githubusercontent.com/assets/1434697/24689640/25298e3a-19c8-11e7-8cc5-1e336fa04ad0.png)

**Comment by mcfarljw** [comment]
I agree that it's currently making too many calls. For reasons relating to #424 we're in between two api's right now. Once we fully migrate do our version 2 api then we'll be consolidating calls. I'm closing this because it's not a client fix directly and is already part of our backend plan.

**Comment by mickem** [comment]
Where do i report backend issues?

Right now the backend design is killing the client...
Having a wrapper (i.e. provide an API which makes all these APIs into a single call for the client) on the backend can be done with any API so not sure your reasoning is valid, more importantly you can cache that in your API manager which will make it very very fast at is it pure static data...
