### ISSUE TITLE
console.error is not error handling

### ISSUE THREAD

**Issue by mickem** [skritter/skritter-html5#425]
This is NOT considered error handling (this is considered sloppy development) to even commit code which use console.log should be prohibited if you need log use a log framework if you need error handling write error handling:

```
      function(error) {
        if (error) {
          console.error('WORD DIALOG LOAD ERROR:', error);
        } else {

...
```

**Comment by mickem** [comment]
BTW, if you search for console.error you find pretty much all the files in the code base...

![image](https://cloud.githubusercontent.com/assets/1434697/24689731/d4de697c-19c8-11e7-81e4-f4fa1bdac160.png)

**Comment by mcfarljw** [comment]
Yes, I agree. It's not great error handling and we should work towards getting those out of the project. I'm a little confused by the screenshot you've provided. It's including things in the `node_modules` folder which are our npm dependencies.

**Comment by mickem** [comment]
Yeah, which is why I removed it, sorry for the confusion...

**Comment by mickem** [comment]
as for "it is useful" a log framework is equally useful, but more importantly showing an error to the user is 100 times as useful and equally simple...

**Comment by mcfarljw** [comment]
Yes, I'm leaving this open so that we can get those placeholder error messages cleaned up that snuck in during development.

**Comment by mickem** [comment]
Closing this as it is not an issue for me...
