### ISSUE TITLE
"My Lists" will sometimes show up empty

### ISSUE THREAD

**Issue by mosteli** [skritter/skritter-html5#439]
Occurred with two tabs of the application open. Repeated reloads of the page did not solve the problem, through closing the application tabs and reopening in one tab restored functionality.

Using web client

**Comment by prokopcm** [comment]
Hi, using multiple tabs of the application creates a new auth token that invalidates the old one. So whichever tab last received a hard refresh will be the only one that can make new requests as the user. I can see something like having My Words or a list section open in a tab on one monitor and the study page open on another, but running multiple instances of the application for the same user simultaneously doesn't seem like a common use case. So while this is something we'd like to improve upon (it's not a pleasant experience that creating a new instance "breaks" the old instance), it's not high priority or show-stopping.

I'll make an internal ticket for this to research improving the token refresh system and discuss it with the rest of the team. Thanks for the report!
