### ISSUE TITLE
Web-version has a lot of words in the words tab, Android has none

### ISSUE THREAD

**Issue by vadimkantorov** [skritter/skritter-html5#444]
And this happens after I tried to reset all progress. Both Android and web-version should have none.

**Comment by prokopcm** [comment]
This sounds like a user-level issue rather than an application-level issue. If you email us at support@skritter.com with some more details we can look into your account and make sure everything's in sync. Thanks!

**Comment by vadimkantorov** [comment]
If I remember well, this happened after I did https://legacy.skritter.com/vocab/deleteall (which comes on Google as first link by query "skritter reset progress").

When I did "Reset my data" (second link on Google), it has removed all words successfully from both web-version.

Unfortunately, I cannot provide more details because I finally managed to purge all data.
